### ISSUE TITLE
README.md vs GitHub Actions

### ISSUE THREAD

**Issue by Sweetchuck** [cweagans/composer-patches#435]
README.md [line 13](https://github.com/cweagans/composer-patches/blob/master/README.md?plain=1#L13)

> Beginning in 2.x, the automated tests will not allow us to use language features
  that will cause syntax errors in PHP 5.6 and later. The unit/acceptance tests do
  not run on anything earlier than PHP 7.1, so while pull requests will be accepted
  for those versions, support is on a best-effort basis.

GitHub Actions [line 14](https://github.com/cweagans/composer-patches/blob/master/.github/workflows/ci.yml#L14)
```yaml
jobs:
  test:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        php: ["8.0", "8.1", "8.2"]
```

I think the README.md is not up to date.
